let data = [
  {
    checked: false,
    checkable: true,
    leaf: true,
    text: 'Category Path',
    value: '',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Elektro',
    value: '995',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Installationsmaterial',
        value: '1174',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Klemmen',
            value: '1175',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Klemmschellen',
            value: '1178',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Schutzrohre',
            value: '1177',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Verschraubungen',
            value: '1176',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Kabel & Leitungen',
        value: '1163',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Schalter & Steckdosen',
        value: '1164',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Smart Home',
        value: '728',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Einzellösungen',
            value: '899',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Heizung',
            value: '896',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Installationszubehör',
            value: '1157',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Lichtsteuerung',
            value: '898',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Rollladensteuerung',
            value: '1156',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Sicherheit',
            value: '897',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Starter Pakete | Sets',
            value: '1158',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Wetter',
            value: '1159',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Stromkreisverteiler',
        value: '1165',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Aufputz',
            value: '1166',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Unterputz',
            value: '1167',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Verteilerbau',
        value: '1168',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Blitzschutz',
            value: '1173',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'FI-Schutzschalter',
            value: '1170',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Hygrostate',
            value: '1172',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Installationsrelais',
            value: '1171',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Sicherungsautomaten',
            value: '1169',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Zubehör',
        value: '1179',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
    ],
  },
  {
    checked: false,
    checkable: true,
    leaf: true,
    text: 'Geschenkgutscheine',
    value: '1161',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Heizung',
    value: '397',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Elektrische Fußbodenheizung',
        value: '411',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Heizmatten',
            value: '910',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Regelung',
            value: '912',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Zubehör',
            value: '913',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Fußbodenheizung',
        value: '398',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Dämmung | Schüttung',
            value: '409',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Dünnschichtsystem',
            value: '403',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Fußbodenheizungsrohr',
            value: '407',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Alu-Verbundrohr',
                value: '603',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'PE-RT Rohr',
                value: '600',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'PE-Xa Rohr',
                value: '602',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'PE-Xc Rohr',
                value: '601',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Rohrverschraubungen',
                value: '604',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Heizkreisverteiler',
            value: '405',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Klettsystem',
            value: '1198',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Komplettsets',
            value: '399',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Montagewerkzeuge',
            value: '410',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Noppensystem',
            value: '401',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Regelung',
            value: '408',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Raumthermostate',
                value: '908',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Regelklemmleisten',
                value: '909',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Stellantriebe',
                value: '605',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Ventilanpassungen für Fremdverteiler',
                value: '823',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Tackersystem',
            value: '400',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Temperaturbegrenzer',
            value: '905',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Mischerstation | Regelstation',
                value: '907',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Rücklauftemperaturbegrenzer',
                value: '906',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Trockenbau-System',
            value: '1194',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Trockenestrichsystem',
            value: '402',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Verteileranbindung',
            value: '598',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Verteilerschränke',
            value: '406',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Zubehör',
            value: '412',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Heizkörper',
        value: '455',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Badheizkörper',
            value: '458',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Flachheizkörper',
            value: '456',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Austauschheizkörper',
                value: '1149',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Kompaktheizkörper (C)',
                value: '620',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Universal-Heizkörper',
                value: '1148',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Ventilheizkörper (VC)',
                value: '621',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Ventilheizkörper Mittelanschluss (VCM)',
                value: '622',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Vertikal-Kompaktheizkörper (CV)',
                value: '619',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Wärmepumpenheizkörper',
                value: '1223',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Infrarotheizkörper',
            value: '457',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Zubehör',
            value: '460',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Hahnblock | Multiblock',
                value: '962',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Rücklaufverschraubung',
                value: '959',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Sonstige',
                value: '963',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Thermostatkopf',
                value: '961',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Thermostatventil',
                value: '960',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Heizlüfter',
        value: '1036',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Solarthermie',
        value: '481',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Flachkollektoren',
            value: '770',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Regelung',
            value: '772',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Röhrenkollektoren',
            value: '769',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Solarrohr',
            value: '773',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Solarspeicher',
            value: '771',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Zubehör',
            value: '774',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Speicher',
        value: '779',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Brauchwasserspeicher',
            value: '781',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Frischwasserstation',
            value: '783',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Hygienespeicher',
            value: '782',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Pufferspeicher',
            value: '780',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Wärmeerzeuger',
        value: '430',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Abgassysteme',
            value: '439',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Kunststoff-Abgassystem',
                value: '941',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Zweiwandiges Abgassystem',
                value: '940',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Elektro-Heizgeräte',
            value: '1221',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Gasheizung',
            value: '431',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Gas-Brennwert',
                value: '918',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Gas-Heizwert',
                value: '917',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Regelung',
                value: '919',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Zubehör',
                value: '920',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Holzheizung',
            value: '927',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Holzvergaser-Heizkessel',
                value: '436',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Hybridheizung',
            value: '1216',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Gas-Hybridheizung',
                value: '1218',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Öl-Hybridheizung',
                value: '1217',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Kaminofen',
            value: '743',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Kaminöfen',
                value: '934',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Kaminöfen Heizungsunterstützung',
                value: '746',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Zubehör',
                value: '936',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Pelletofen',
            value: '753',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Zubehör',
                value: '759',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Wärmepumpe',
            value: '435',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Brauchwasserwärmepumpe',
                value: '438',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Luft-Wasser-Wärmepumpe',
                value: '617',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Sole-Wärmepumpe',
                value: '616',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Zubehör',
                value: '1001',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Ölheizung',
            value: '432',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Zubehör',
                value: '925',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Öl-Brennwert',
                value: '922',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Öl-Heizwert',
                value: '921',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Öltanks',
                value: '433',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    checked: false,
    checkable: true,
    leaf: true,
    text: 'Inactive',
    value: 'Inactive',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Installation',
    value: '1201',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Abwasserinstallation',
        value: '984',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'HT-Rohr',
            value: '986',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'KG-Rohr',
            value: '985',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Heizungsinstallation',
        value: '942',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Ausdehnungsgefäße',
            value: '479',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Heizungsarmaturen',
            value: '943',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Heizungspumpen',
            value: '949',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Kondensathebeanlage',
                value: '952',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Umwälzpumpe',
                value: '951',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Zirkulationspumpe',
                value: '950',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Heizungsverteiler | Kesselverteiler',
            value: '948',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Luftblasenabscheider',
            value: '946',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Mischer | Regler',
            value: '954',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Pumpengruppe',
            value: '947',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Schlammabscheider',
            value: '945',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Sicherheitsgruppe',
            value: '944',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Sonstige | Zubehör',
            value: '440',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Wärmemengenzähler',
            value: '820',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Sanitärinstallation',
        value: '526',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Absperrventile',
            value: '983',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Armaturen',
            value: '717',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Durchlauferhitzer / Untertischgeräte',
            value: '721',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Panzerschlauch',
            value: '714',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Vorwandinstallationssystem',
            value: '720',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Wasserzähler',
            value: '718',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Zubehör',
            value: '1000',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Zubehör',
        value: '1202',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
    ],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Lüftung',
    value: '483',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Dezentrale Lüftungsanlagen',
        value: '555',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Außenhaube',
            value: '974',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Einbauhülsen | Wandhülsen',
            value: '972',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Komplettsets',
            value: '1160',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Luftdruckwächter',
            value: '975',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Luftfilter',
            value: '973',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Lüftungsgeräte',
            value: '572',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Regelung',
            value: '565',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Zubehör',
            value: '976',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Dienstleistungen',
        value: '1126',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Kleinraumventilatoren',
        value: '581',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Einbauhülsen | Wandhülsen',
            value: '979',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Geräte',
            value: '977',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Regelung',
            value: '978',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Zubehör',
            value: '980',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Luftreiniger',
        value: '1192',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Zentrale Lüftungsanlagen',
        value: '487',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Außenluft | Fortluft',
            value: '516',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Enthalpietauscher',
            value: '1048',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Luftdruckwächter',
            value: '1046',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Lufteinlässe | Luftauslässe',
            value: '515',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Luftfilter',
            value: '970',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Luftverteiler',
            value: '966',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Lüftungsgeräte',
            value: '965',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Lüftungsrohre',
            value: '967',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Flachkanal',
                value: '968',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Kunststoff-Flexrohr',
                value: '969',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Schaumrohr | Luftschlauch',
                value: '513',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Montagesets',
            value: '1187',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Regelung',
            value: '1045',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Schalldämpfer',
            value: '514',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: false,
            text: 'Sets',
            value: '964',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Komplettsets',
                value: '1211',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Sets Außenluft | Fortluft',
                value: '1213',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
              {
                checked: false,
                checkable: true,
                leaf: true,
                text: 'Sets Lufteinlässe | Luftauslässe',
                value: '1212',
                categoryProperty: null,
                alignmentIndices: null,
                marginIndices: null,
                weightIndices: null,
                children: [],
              },
            ],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Zubehör',
            value: '971',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Mehr...',
    value: '525',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'B-Ware',
        value: '1184',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Baustoffe',
        value: '740',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Estrich',
            value: '742',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Klima',
        value: '990',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Klimaboxen',
            value: '992',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Klimageräte',
            value: '991',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Regenwassernutzung',
        value: '785',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Pumpen',
            value: '1022',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Regelung',
            value: '1017',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Zubehör',
            value: '1023',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Schornsteine',
        value: '522',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'DN 100',
            value: '760',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'DN 130',
            value: '761',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'DN 150',
            value: '762',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'DN 180',
            value: '763',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'DN 200',
            value: '764',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Werkzeuge | Maschinen | Geräte',
        value: '521',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Mietgeräte',
            value: '894',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Neuwerkzeuge',
            value: '795',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Planungsservice',
    value: '1134',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Heizung',
        value: '1136',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Heizflächenauslegung',
            value: '1153',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Heizlastberechnung',
            value: '1152',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Verlegeplan',
            value: '1154',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Pumpen',
    value: '484',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Druckerhöhungsanlage',
        value: '655',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Fäkalienhebeanlage',
        value: '651',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Gartenpumpe',
        value: '654',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Kleinhebeanlage Abwasser',
        value: '638',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Kleinhebeanlage Schmutzwasser',
        value: '642',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Kleinhebeanlagen',
        value: '1132',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Kondensathebeanlage',
        value: '649',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Pumpengruppen',
        value: '862',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Pumpenverschraubungen',
        value: '658',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Schmutzwassertauchpumpe',
        value: '646',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Solarpumpe',
        value: '656',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Umwälzpumpe Heizung',
        value: '634',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Zirkulationspumpe Brauchwasser',
        value: '629',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Zisternenpumpe',
        value: '653',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
    ],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Rohrsysteme',
    value: '520',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Aluverbund',
        value: '689',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Press-System',
            value: '690',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Rohr',
            value: '693',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Steck-System',
            value: '691',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Steck-System Verteiler Heizung / Sanitär',
            value: '692',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Dichtstoffe',
        value: '713',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Edelstahl',
        value: '700',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Steck-System',
            value: '701',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Kupfer',
        value: '695',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Press-System',
            value: '696',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Rohr',
            value: '698',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Steck-System',
            value: '697',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: false,
        text: 'Messing',
        value: '1196',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [
          {
            checked: false,
            checkable: true,
            leaf: true,
            text: 'Gewinde-System',
            value: '1197',
            categoryProperty: null,
            alignmentIndices: null,
            marginIndices: null,
            weightIndices: null,
            children: [],
          },
        ],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Rohrbegleitheizung',
        value: '1193',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Rohrisolierung',
        value: '702',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Rohrschellen',
        value: '703',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Zubehör',
        value: '704',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
    ],
  },
  {
    checked: false,
    checkable: true,
    leaf: true,
    text: 'Rupio',
    value: '1189',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Selfio kreativ',
    value: '802',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'DIY-Werkzeug',
        value: '809',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Einzelteile',
        value: '808',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Kaffeezubereiter',
        value: '806',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Kerzenständer',
        value: '804',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Tablethalter',
        value: '805',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Toilettenpapierhalter',
        value: '807',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
    ],
  },
  {
    checked: false,
    checkable: true,
    leaf: false,
    text: 'Wasseraufbereitung',
    value: '485',
    categoryProperty: null,
    alignmentIndices: null,
    marginIndices: null,
    weightIndices: null,
    children: [
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Dosierlösungen / Salze',
        value: '982',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Dosiertechnik',
        value: '891',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Enthärtungsanlagen',
        value: '889',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Feinfilter / Rückspülfilter',
        value: '890',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Heizungsschutz',
        value: '892',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
      {
        checked: false,
        checkable: true,
        leaf: true,
        text: 'Selfio Watersoft Enthärtungsanlagen',
        value: '1183',
        categoryProperty: null,
        alignmentIndices: null,
        marginIndices: null,
        weightIndices: null,
        children: [],
      },
    ],
  },
];
let finalData = [];
data.slice(1).forEach((data, mIndex) => {
  let mainText = data.text;
  if (data.children) {
    finalData.push({
      name: mainText,
      subCategories: data.children.map((subCategory) => {
        if (subCategory.children) {
          return {
            name: subCategory.text,
            childCategories: subCategory.children.map((child) => ({
              name: child.text,
            })),
          };
        } else {
          return subCategory;
        }
      }),
    });
  } else {
    finalData.push({ name: mainText });
  }
});
console.log(finalData);
